resources:
  - deployment.yaml
  - configmap.yaml

secretGenerator:
  - name: abc
    envs:
      - secret.env
    options:
      annotations:
        ccoe-secretengine.kubernetes.io/path: remote-templates
